### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by arnabwahid** [aurelienpierre/wp-scholar#1]
```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp-scholar-load-textdomain' not found or invalid function name in C:\Users\arnab\Local Sites\blog\app\public\wp-includes\class-wp-hook.php on line 303
```
When I activate the plugin, I am getting this error. @aurelienpierre Could you please tell me how I can fix this?

**Comment by aurelienpierre** [comment]
This is a warning, not an error. You shouldn't have WP_DEBUG enabled on a production site. In `wp-config.php`, you need to find `define ('WP_DEBUG', true);` and set it to  `define ('WP_DEBUG', false);`

**Comment by arnabwahid** [comment]
The site is on my localhost (Trying to figure out how to turn my notebooks into blog posts 😄 ).
Thanks a lot. I think it was turned on by default by the application I am using. I will disable WP_DEBUG.
